# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
    ]
