# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiling', '0002_auto_20180629_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(related_name='user_skills', to='user_profiling.UserProfile')),
            ],
        ),
    ]
